apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
spec:
  selector:
    matchLabels:
      app: busybox
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: busybox
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - name: busybox
        image: busybox:1.31.1
        volumeMounts:
        - name: shared-data
          mountPath: /var/www
      - name: nginx
        image: nginx:1.17.9
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
