apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      initContainers:
      - name: busybox
        image: busybox:1.31.1
        volumeMounts:
        - name: shared-data
          mountPath: /var/www
        command: ["/bin/sh", "-c"]
        args:
        - echo "Hello from the busybox initContainer" > /var/www/index.html
      containers:
      - name: nginx
        image: nginx:1.17.9
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
      - name: debian
        image: debian:bullseye
        volumeMounts:
        - name: shared-data
          mountPath: /mnt/html
        command: ["/bin/bash", "-c"]
        args:
        - while true; do
            sleep 30;
          done
