apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - image: bitnami/elasticsearch:6
        name: elasticsearch
        envFrom:
        - configMapRef:
            name: elasticsearch
        ports:
        - containerPort: 9200
          name: elasticsearch
        volumeMounts:
        - name: elasticsearch-persistent-storage
          mountPath: /bitnami/elasticsearch/data
      volumes:
      - name: elasticsearch-persistent-storage
        persistentVolumeClaim:
          claimName: elasticsearch-pv-claim
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
