apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.1
        name: elasticsearch
        envFrom:
        - configMapRef:
            name: elasticsearch
        ports:
        - name: http
          containerPort: 9200
        - name: transport
          containerPort: 9300
