apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pv-claim
spec:
  storageClassName: manual
  volumeName: elasticsearch-pv-volume
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
