apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
spec:
  storageClassName: manual
  volumeName: mariadb-pv-volume
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
