apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
spec:
  selector:
    matchLabels:
      app: busybox
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: busybox
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - name: nginx
        image: nginx:1.17.9
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
      - name: debian
        image: debian:bullseye
        volumeMounts:
        - name: shared-data
          mountPath: /mnt/html
