apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/mysql"
