apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento
spec:
  selector:
    matchLabels:
      app: magento
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: magento
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: magento-persistent-storage
        persistentVolumeClaim:
          claimName: magento-pv-claim
      initContainers:
      - name: magento-content
        image: rainchei/docker-magento:1.0.0-27-g98ef141-20200317
        volumeMounts:
        - name: shared-data
          mountPath: /mnt/
        command: ["/bin/bash", "-c"]
        args:
        - mv /var/www/magento2 /mnt/magento2
      containers:
      - name: magento-nginx
        image: nginx:1.17.9
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
        - name: magento-persistent-storage
          mountPath: /usr/share/nginx/html/pub/media
        ports:
        - containerPort: 80
      - name: magento-phpfpm
        image: rainchei/docker-magento:1.0.0-27-g98ef141-20200317
        volumeMounts:
        - name: shared-data
          mountPath: /var/www/magento2
        - name: magento-persistent-storage
          mountPath: /var/www/magento2/pub/media
        envFrom:
        - configMapRef:
            name: magento
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 1024Mi
