apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento
spec:
  selector:
    matchLabels:
      app: magento
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: magento
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: shared-pipe
        emptyDir: {}
      - name: magento-persistent-storage
        persistentVolumeClaim:
          claimName: magento-pv-claim
      initContainers:
      - name: magento-content
        image: rainchei/docker-magento-phpfpm:1.0.0-62-gb85dd20-20200318
        volumeMounts:
        - name: shared-data
          mountPath: /mnt/
        command: ["/bin/bash", "-c"]
        args:
        - mv /var/www/magento2/* /mnt/
      containers:
      - name: magento-nginx
        image: rainchei/docker-magento-nginx:1.0.0-63-g71a720a-20200318
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
        - name: shared-pipe
          mountPath: /var/run/php
        - name: magento-persistent-storage
          mountPath: /usr/share/nginx/html/pub/media
        ports:
        - containerPort: 80
      - name: magento-phpfpm
        image: rainchei/docker-magento-phpfpm:1.0.0-62-gb85dd20-20200318
        volumeMounts:
        - name: shared-data
          mountPath: /var/www/magento2
        - name: shared-pipe
          mountPath: /var/run/php
        - name: magento-persistent-storage
          mountPath: /var/www/magento2/pub/media
        envFrom:
        - configMapRef:
            name: magento
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 1024Mi
