apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento
spec:
  selector:
    matchLabels:
      app: magento
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: magento
    spec:
      volumes:
      - name: magento-persistent-storage
        persistentVolumeClaim:
          claimName: magento-pv-claim
      containers:
      - name: magento
        image: rainchei/docker-magento:1.0.0-12-g95e419a-20200315
        envFrom:
        - configMapRef:
            name: magento
        volumeMounts:
        - name: magento-persistent-storage
          mountPath: /var/www/html/pub/media
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 1024Mi
