apiVersion: v1
kind: Service
metadata:
  name: magento
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    nodePort: 443
  - name: http
    port: 80
    nodePort: 80
  selector:
    app: magento
